### PR TITLE
Create Adguard-home.txt

### PR DESCRIPTION
**Pull request by michaelb-ae**
i propose to you this adguard syntaxed list, for all adblocker who understand it, and adguard home (like pihole) who understand it too.

### CODE REVIEW

**Comment by michaelb-ae** [comment]
for not destroying the mirroring of other rules i have (my script) founded some duplicate there is the list :

||crcdn01.adnxs.com^
||revolutetech.g2afse.com^
||go2.enjoycpi.com^
||fd.allsaintsyrt.club^
||clk.apxtrk.com^
||track.hexcan.com^
||aandb.g2afse.com^
||cronbaytech.g2afse.com^
||gmthub.g2afse.com^
||clk.dotctracking.info^
||go2.starklito.com^
||tlv3.holmjoil.online^
||chimaprome.com^
||8sc13bd.appsdeku.com^
||7a02kdk.mapucamonga.com^
||blueparrot.xml.ak-is2.net^
||clk.trk144.com^
||newlb.weq.com^
||track.mialltrack2.com^
||digiaff.affise.com^
||a1o1jaw.appsdeku.com^
||trk.keepfollowthelight.online^
||go.awesomepathfinder.site^
||cornerstore.g2afse.com^
||oneenginemedia.g2afse.com^
||click.kanmobi.net^
||click.appsamurai.com^
||apply.g2afse.com^
||appalgo.g2afse.com^
||click.baburnadir.com^
||spykemedia.g2afse.com^
||appmedia.g2afse.com^
||if.singularityfds.club^
||click.clickmara.com^
||limpid.g2afse.com^
||bv.strandnm.xyz^
||go.g2app.net^
||ttmma.g2afse.com^
||appnapp.g2afse.com^
||lb63.s400.meetrics.net^
||m.addthisedge.com^

**Comment by BlackJack8** [comment]
Hi there, thanks for your effort! Since i`ve added quite a lot of domains to my list recently, i probably need to format and deduplicate the list myself as i can't keep track of what i did and did not add. I already uploaded the updated list and if you find anything unusual, you can create a pull request and i will merge it.

**Comment by michaelb-ae** [comment]
sure @BlackJack8 if you want you can deduplicate with VScode and the extension "dupChecker", open the file to deduplicate F1 start to type " check duplicate " select it and enter, it will tell you if he have found duplicate and even propose to remove it.

**Comment by BlackJack8** [comment]
Alright, i will fix that right away. Thank you very much for helping!

**Comment by michaelb-ae** [comment]
its normal, i know duplicate is very hard do deal with so using extension or script to help is always welcome when the list is more than 10 thousands of domain name :)

**Pull request closed without merging**
