### PR TITLE
add csv list for Adblock iOS App

### PR DESCRIPTION
**Pull request by insuusvenerati**
The App I use requires CSV so perhaps other apps will use it as well. Created by taking the Hosts.txt and replacing \n with ,

### CODE REVIEW

**Comment by asaddon** [comment]
Adblock can use Hosts.txt file without any issues, I don't think any other format is needed.

**Comment by insuusvenerati** [comment]
Strange because I tried it and got an error.

**Comment by insuusvenerati** [comment]
Never mind. I was linking to the wrong url.

**Comment by BlackJack8** [comment]
I can still make a CSV Format List, but the question is if people actually use adblockers that need CSV.

**Pull request closed without merging**
